info:
  contact:
    email: arielbrizi@gmail.com
    name: API Support
    url: https://arielbrizi.github.io/go-intelligent-monitoring-system/
  description: Configuration and Analize Services.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Intelligent Monitoring System
  version: "1.0"
paths:
  /configuration-core/authorized-face:
    delete:
      consumes:
      - application/json
      description: delete the person in the image (parameter) as an authorized face
      parameters:
      - description: Authorized FaceId
        in: path
        name: name
        required: true
        type: string
      - description: Collection ID
        in: path
        name: collection
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: delete authorized face
      tags:
      - configuration-core
    post:
      consumes:
      - application/json
      description: add the person in the image (parameter) as an authorized face
      parameters:
      - description: Image File Name with extension
        in: path
        name: name
        required: true
        type: string
      - description: Bucket ID
        in: path
        name: bucket
        required: true
        type: string
      - description: Collection ID
        in: path
        name: collection
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: add authorized face
      tags:
      - configuration-core
  /configuration-core/authorized-face/{collectionName}:
    get:
      consumes:
      - application/json
      description: get the authorized faces for collection Id
      parameters:
      - description: Collection ID
        in: path
        name: collection
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: get authorized faces
      tags:
      - configuration-core
swagger: "2.0"
