name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        TZ: America/Argentina/Buenos_Aires
        AWS_ACCESS_KEY_ID: XXX
        AWS_SECRET_ACCESS_KEY: XXX
        FTP_DIRECTORY: /home/ariel/fotos_pasillo/
        CAMARA_DOMAIN: camarasilvia
        QUEUE_TOPIC: images
        QUEUE_BROKER_LIST: broker:9092
        SNS_TOPIC: arn:aws:sns:us-east-1:491728392546:monitoringSystem-eMail
        AUTHORIZED_FACES_DIRECTORY: /home/ariel/fotos_pasillo/authorized_faces/
      run: go test -v ./...
